theme: jekyll-theme-minimal
title: Nazlı'nın Bloğu
url : https://github.com/nazliyanik
email: nazliyanik52@gmail.com
github_username : nazliyanik

layout: page
title: "Hakkımda "
permalink: /https://nazliyanik.github.io/about.me/
